"""
Bundles a generated agent into a self-contained output directory.

Output structure:
  outputs/<agent-name>/
    .cursorrules
    tests/
      test_cases.json
      test_runner.py
    benchmarks.json
    README.md
"""

import json
import os
import re
from typing import List

from src.test_suite_builder import TestCase
from src.benchmark_engine import BenchmarkResults, results_to_dict
from src.test_suite_builder import test_cases_to_dict


def _slugify(name: str) -> str:
    """Convert agent description to a filesystem-safe slug."""
    slug = name.lower().strip()
    slug = re.sub(r"[^\w\s-]", "", slug)
    slug = re.sub(r"[\s_]+", "-", slug)
    slug = re.sub(r"-+", "-", slug)
    return slug[:60].strip("-")


def _generate_readme(
    agent_name: str,
    description: str,
    benchmarks: dict,
    num_tests: int,
) -> str:
    score = benchmarks.get("performance_score", 0)
    custom_acc = benchmarks.get("custom_accuracy", 0)
    default_acc = benchmarks.get("default_accuracy", 0.65)
    improvement = benchmarks.get("improvement_percent", 0)
    components = benchmarks.get("component_scores", {})

    return f"""# {agent_name}

> Generated by Cursor Agent Factory

## Description
{description}

## Performance Score: {score}/10,000

| Metric | Default Cursor | This Agent | Improvement |
|--------|---------------|------------|-------------|
| Accuracy | {default_acc:.0%} | {custom_acc:.0%} | +{improvement:.1f}% |
| Test Cases | — | {num_tests} | — |

### Score Breakdown

| Component | Score | Max |
|-----------|-------|-----|
| Generation Quality | {components.get('generation_quality', 0)} | 3000 |
| Benchmark Performance | {components.get('benchmark_performance', 0)} | 3000 |
| Time Efficiency | {components.get('time_efficiency', 0)} | 2000 |
| Cursor Integration | {components.get('cursor_integration', 0)} | 1500 |
| Innovation | {components.get('innovation', 0)} | 500 |
| **Total** | **{score}** | **10000** |

## Usage

1. Copy `.cursorrules` to your project root
2. Open project in Cursor
3. The agent will automatically apply its rules

## Files

- `.cursorrules` — Agent rules (drop into your project)
- `tests/test_cases.json` — {num_tests} test cases
- `tests/test_runner.py` — Automated test runner
- `benchmarks.json` — Full benchmark data

## Generated by
[Cursor Agent Factory](https://github.com/yourusername/cursor-agent-factory)
"""


def _generate_test_runner(agent_name: str) -> str:
    return f'''"""
Automated test runner for {agent_name}.
Run: pytest tests/test_runner.py
"""

import json
import os
import pytest

TEST_CASES_PATH = os.path.join(os.path.dirname(__file__), "test_cases.json")


def load_test_cases():
    with open(TEST_CASES_PATH) as f:
        return json.load(f)


@pytest.mark.parametrize("tc", load_test_cases())
def test_case_has_required_fields(tc):
    assert "code" in tc, "Test case missing 'code' field"
    assert "expected_result" in tc, "Test case missing 'expected_result'"
    assert tc["expected_result"] in ("pass", "fail"), \\
        f"expected_result must be 'pass' or 'fail', got {{tc['expected_result']}}"
    assert "reason" in tc, "Test case missing 'reason'"
    assert len(tc["code"]) > 0, "Test case code is empty"


@pytest.mark.parametrize("tc", load_test_cases())
def test_case_code_is_non_trivial(tc):
    assert len(tc["code"].strip()) >= 10, \\
        f"Test case code too short: {{tc['code']!r}}"
'''


def package_agent(
    description: str,
    cursorrules: str,
    test_cases: List[TestCase],
    benchmark_results: BenchmarkResults,
    output_base: str = "outputs",
) -> str:
    """
    Write all agent files to outputs/<slug>/.

    Args:
        description: Natural language agent description.
        cursorrules: Generated .cursorrules content.
        test_cases: List of TestCase objects.
        benchmark_results: BenchmarkResults from benchmark_engine.
        output_base: Parent directory for outputs (default: "outputs").

    Returns:
        Path to the output directory.
    """
    slug = _slugify(description)
    agent_name = slug.replace("-", " ").title()
    output_dir = os.path.join(output_base, slug)
    tests_dir = os.path.join(output_dir, "tests")

    os.makedirs(tests_dir, exist_ok=True)

    # .cursorrules
    with open(os.path.join(output_dir, ".cursorrules"), "w", encoding="utf-8") as f:
        f.write(cursorrules)

    # benchmarks.json
    bench_dict = results_to_dict(benchmark_results)
    with open(os.path.join(output_dir, "benchmarks.json"), "w", encoding="utf-8") as f:
        json.dump(bench_dict, f, indent=2)

    # tests/test_cases.json
    tc_list = test_cases_to_dict(test_cases)
    with open(os.path.join(tests_dir, "test_cases.json"), "w", encoding="utf-8") as f:
        json.dump(tc_list, f, indent=2)

    # tests/test_runner.py
    with open(os.path.join(tests_dir, "test_runner.py"), "w", encoding="utf-8") as f:
        f.write(_generate_test_runner(agent_name))

    # README.md
    readme = _generate_readme(agent_name, description, bench_dict, len(test_cases))
    with open(os.path.join(output_dir, "README.md"), "w", encoding="utf-8") as f:
        f.write(readme)

    return output_dir
